### ISSUE TITLE
False failing for certain json content

### ISSUE THREAD

**Issue by idanen** [duailibe/jest-json#15]
Example: https://codesandbox.io/s/jest-json-fails-id-eq47ic

When one of the field's values is `'id'` the matching falsly fails.

**Comment by duailibe** [comment]
@idanen It looks like that example is running with Jest 26, and jest-json only works with Jest >= 27.2.5

**Comment by duailibe** [comment]
You can also check it by using any other value instead of `'id'` and seeing that it will fail as well

**Comment by idanen** [comment]
This happened in our product also, so maybe I didn't find the right reproduction.
I'll try to find it
